version: "3.8"
services:
  wolweb:
    container_name: wolweb
    build: .
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - ./devices.json:/wolweb/devices.json
      - ./config.json:/wolweb/config.json

    network_mode: host
    restart: unless-stopped


